name: CI

on:
  pull_request:
    branches: [ main, dev ]
  
  push:
    branches: [ main, dev ]
  
  workflow_dispatch:

jobs:
  quality:
    name: Quality Checks
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Install uv
        uses: astral-sh/setup-uv@v3
      
      - name: Set up Python
        run: uv python install 3.12
      
      - name: Set up virtual environment
        run: |
          uv venv .venv;
          source ./.venv/bin/activate

      - name: Install dependencies
        run: |
          uv tool install ruff;
          uv pip install pytest
      
      - name: Ruff format check
        run: ruff format --check .
      
      - name: Ruff lint
        run: ruff check --cache-dir .ruff_cache .
      
      - name: Run tests
        run: uv run pytest
      
      - name: Check Markdown format
        uses: DavidAnson/markdownlint-cli2-action@v16
        with:
          globs: '**/*.md --ignore .github/**'
      
      - name: Check YAML format
        uses: ibiqlik/action-yamllint@v3
        with:
          file_or_dir: .
          config_data: |
            extends: default
            rules:
              line-length: disable
              document-start: disable
      
      - name: Check TOML format
        run: |
          uv pip install taplo
          taplo check
      
      - name: Cache uv
        uses: actions/cache@v3
        with:
          path: ~/.cache/uv
          key: ${{ runner.os }}-uv-${{ hashFiles('**/pyproject.toml') }}
